name: Check
description: Lints & formats

runs:
  using: composite
  steps:
    - name: fmt
      shell: bash
      run: cargo fmt --all -- --check

    - name: clippy
      shell: bash
      run: cargo clippy --workspace -- -D warnings
